name: Daily Update Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,14 * * *'  # 每天的 UTC 时间 2 点和 14 点运行，对应 UTC+8 时间的 10 点和 22 点


jobs:
  update-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: python AutoJetBrainsLicense.py
      
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Update
